import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsOptional, IsString, IsUUID } from 'class-validator';

/**
 * FiscalReceiptResponseDto — stub for B13.
 *
 * In B13 all receipts are generated by `MockFiscalReceiptAdapter` and have
 * `ofd_status='queued'` / `fiscal_sign='mock_*'`. Full OFD integration
 * (Kassa24, Rekassa, Webkassa) and the retry/report endpoints ship in B15.
 */
export class FiscalReceiptResponseDto {
  @ApiProperty({ example: 'fr1a2b3c-0009-0009-0009-000000000009' })
  id!: string;

  @ApiProperty({ example: 'pa1b2c3d-0007-0007-0007-000000000007' })
  payment_id!: string;

  @ApiProperty({ example: '00000000-0000-0000-0000-000000000001' })
  kindergarten_id!: string;

  @ApiProperty({
    example: 'mock_fiscal_sign_abc123',
    description: 'Unique fiscal sign / QR token returned by the OFD.',
  })
  fiscal_sign!: string;

  @ApiProperty({
    example: 'queued',
    enum: ['queued', 'sent', 'failed'],
    description: 'OFD submission status.',
  })
  ofd_status!: 'queued' | 'sent' | 'failed';

  @ApiProperty({
    example: 'https://ofd.kz/receipts/mock_fiscal_sign_abc123',
    nullable: true,
    description:
      'QR code URL pointing to the OFD receipt page. Null while status=queued.',
  })
  qr_url!: string | null;

  @ApiProperty({ example: 'mock', description: 'OFD provider identifier.' })
  provider!: string;

  @ApiProperty({ example: '2026-06-10T12:00:00.000Z' })
  created_at!: string;
}

export class ListFiscalReceiptsQueryDto {
  @ApiProperty({
    example: 'queued',
    enum: ['queued', 'sent', 'failed'],
    description: 'Filter by OFD status.',
    required: false,
  })
  @IsOptional()
  @IsEnum(['queued', 'sent', 'failed'])
  status?: 'queued' | 'sent' | 'failed';

  @ApiProperty({
    example: 'mock',
    description: 'Filter by OFD provider.',
    required: false,
  })
  @IsOptional()
  @IsString()
  provider?: string;

  @ApiProperty({
    example: 'pa1b2c3d-0007-0007-0007-000000000007',
    description: 'Filter by payment.',
    required: false,
  })
  @IsOptional()
  @IsUUID()
  payment_id?: string;

  @ApiProperty({
    example: 'mock_fiscal_sign_abc123',
    description: 'Filter by fiscal sign.',
    required: false,
  })
  @IsOptional()
  @IsString()
  fiscal_sign?: string;
}
