import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsDateString,
  IsEnum,
  IsInt,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  IsUrl,
  Matches,
  Max,
  Min,
  ValidateIf,
} from 'class-validator';
import type {
  PaymentProvider,
  PaymentStatus,
} from '../domain/entities/payment.entity';

const PAYMENT_PROVIDERS: PaymentProvider[] = [
  'mock',
  'halyk_epay',
  'kaspi_pay',
  'tiptoppay',
  'freedom_pay',
  'bcc',
  'cash',
];

const PAYMENT_STATUSES: PaymentStatus[] = [
  'initiated',
  'processing',
  'completed',
  'failed',
  'refunded',
];

const PAYMENT_MODES = ['full', 'partial'] as const;
type PaymentMode = (typeof PAYMENT_MODES)[number];

export class InitiatePaymentDto {
  @ApiProperty({
    enum: PAYMENT_PROVIDERS,
    example: 'mock',
    description:
      'Payment provider. Use "mock" for dev/test; "cash" is admin-only.',
  })
  @IsEnum(PAYMENT_PROVIDERS)
  provider!: PaymentProvider;

  @ApiProperty({
    enum: PAYMENT_MODES,
    example: 'full',
    description:
      'full — pays the full remaining balance; partial — requires amount field.',
  })
  @IsEnum(PAYMENT_MODES)
  payment_mode!: PaymentMode;

  @ApiProperty({
    example: 60000,
    description:
      'Required when payment_mode=partial. Must be > 0 and < remaining balance.',
    required: false,
    nullable: true,
    minimum: 1,
  })
  @IsOptional()
  @IsNumber()
  @Min(1)
  amount?: number | null;

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description:
      'UUID v4 generated by the client per payment attempt. Ensures idempotency — repeating with the same key returns the existing payment_id without creating a duplicate.',
  })
  @IsUUID()
  idempotency_key!: string;

  @ApiProperty({
    example: 'https://app.shyraq.kz/payment/callback',
    description: 'URL the provider redirects to after the payment page.',
  })
  @IsUrl()
  return_url!: string;

  @ApiProperty({
    example: '77011234567',
    required: false,
    description:
      'Required when provider=kaspi_pay — phone Kaspi sends the remote invoice to. Ignored for other providers.',
  })
  @ValidateIf((o: InitiatePaymentDto) => o.provider === 'kaspi_pay')
  @IsString()
  @Matches(/^7\d{10}$/, { message: 'invalid_phone_format' })
  kaspi_phone_number?: string;
}

export class InitiatePrepaymentDto {
  @ApiProperty({
    enum: [3, 6, 12, 24],
    example: 3,
    description:
      'Number of months to prepay. Must match an available prepay_*m_pct in the active tariff discount_rules.',
  })
  @IsInt()
  @IsEnum([3, 6, 12, 24])
  months!: 3 | 6 | 12 | 24;

  @ApiProperty({
    enum: PAYMENT_PROVIDERS,
    example: 'mock',
    description: 'Payment provider for the prepayment.',
  })
  @IsEnum(PAYMENT_PROVIDERS)
  provider!: PaymentProvider;

  @ApiProperty({
    example: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    description: 'Client-generated UUID v4 idempotency key.',
  })
  @IsUUID()
  idempotency_key!: string;

  @ApiProperty({
    example: 'https://app.shyraq.kz/payment/prepayment/callback',
    description: 'Redirect URL after provider payment page.',
  })
  @IsUrl()
  return_url!: string;

  @ApiProperty({
    example: '77011234567',
    required: false,
    description:
      'Required when provider=kaspi_pay — phone Kaspi sends the remote invoice to. Ignored for other providers.',
  })
  @ValidateIf((o: InitiatePrepaymentDto) => o.provider === 'kaspi_pay')
  @IsString()
  @Matches(/^7\d{10}$/, { message: 'invalid_phone_format' })
  kaspi_phone_number?: string;
}

// ── query DTO ──────────────────────────────────────────────────────────────

export class ListPaymentsQueryDto {
  @ApiProperty({
    enum: PAYMENT_PROVIDERS,
    example: 'halyk_epay',
    description: 'Filter by payment provider.',
    required: false,
  })
  @IsOptional()
  @IsEnum(PAYMENT_PROVIDERS)
  provider?: PaymentProvider;

  @ApiProperty({
    enum: PAYMENT_STATUSES,
    example: 'completed',
    description: 'Filter by payment status.',
    required: false,
  })
  @IsOptional()
  @IsEnum(PAYMENT_STATUSES)
  status?: PaymentStatus;

  @ApiProperty({
    example: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
    description: 'Filter by child.',
    required: false,
  })
  @IsOptional()
  @IsUUID()
  child_id?: string;

  @ApiProperty({
    example: 'true',
    description:
      'Pass "true" to return only payments flagged as needing a manual refund (double payments).',
    required: false,
  })
  @IsOptional()
  @IsString()
  refund_required?: string;

  @ApiProperty({
    example: '2026-06-01',
    description: 'Return payments with paid_at or created_at >= this date.',
    required: false,
  })
  @IsOptional()
  @IsDateString()
  from_date?: string;

  @ApiProperty({
    example: '2026-06-30',
    description: 'Return payments with paid_at or created_at <= this date.',
    required: false,
  })
  @IsOptional()
  @IsDateString()
  to_date?: string;

  @ApiProperty({
    example: 'eyJpZCI6InV1aWQifQ==',
    description: 'Pagination cursor from previous response.',
    required: false,
  })
  @IsOptional()
  @IsString()
  cursor?: string;

  @ApiProperty({
    example: 50,
    description: 'Page size (default 50, max 200).',
    required: false,
    minimum: 1,
    maximum: 200,
  })
  @IsOptional()
  @IsInt()
  @Min(1)
  @Max(200)
  @Type(() => Number)
  limit?: number;
}

// ── response DTOs ──────────────────────────────────────────────────────────

export class PaymentResponseDto {
  @ApiProperty({ example: 'pa1b2c3d-0007-0007-0007-000000000007' })
  id!: string;

  @ApiProperty({ example: '00000000-0000-0000-0000-000000000001' })
  kindergarten_id!: string;

  @ApiProperty({ example: 'i1a2b3c4-0005-0005-0005-000000000005' })
  invoice_id!: string;

  @ApiProperty({ example: 'cccccccc-cccc-cccc-cccc-cccccccccccc' })
  child_id!: string;

  @ApiProperty({
    example: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    nullable: true,
    description: 'User who initiated the payment. Null for system-generated.',
  })
  payer_user_id!: string | null;

  @ApiProperty({ example: 120000, description: 'Amount paid in KZT.' })
  amount!: number;

  @ApiProperty({ enum: PAYMENT_PROVIDERS, example: 'mock' })
  provider!: PaymentProvider;

  @ApiProperty({
    example: 'MOCK-TXN-0001',
    nullable: true,
    description: 'Transaction id assigned by the provider.',
  })
  provider_txn_id!: string | null;

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description: 'Client-supplied idempotency key.',
  })
  idempotency_key!: string;

  @ApiProperty({ enum: PAYMENT_STATUSES, example: 'completed' })
  status!: PaymentStatus;

  @ApiProperty({
    example: '2026-06-10T12:00:00.000Z',
    nullable: true,
    description: 'Timestamp when payment was confirmed.',
  })
  paid_at!: string | null;

  @ApiProperty({
    example: null,
    nullable: true,
    description: 'Linked refund id if the payment was refunded.',
  })
  refund_id!: string | null;

  @ApiProperty({
    example: false,
    description:
      'True when this completed payment is a duplicate (another guardian already paid the same invoice) and needs a manual admin refund. Show "Нужен возврат" in the admin app.',
  })
  refund_required!: boolean;

  @ApiProperty({
    example: 'double_payment',
    nullable: true,
    description:
      'Why a refund is required (e.g. double_payment). Null otherwise.',
  })
  refund_reason!: string | null;

  @ApiProperty({
    example: 'pa1b2c3d-0006-0006-0006-000000000006',
    nullable: true,
    description:
      'The FIRST (kept) payment this one duplicates — link to it in the admin app ("Двойная оплата, см. оплату <id>"). Null when not a duplicate.',
  })
  duplicate_of_payment_id!: string | null;

  @ApiProperty({ example: '2026-06-10T11:55:00.000Z' })
  created_at!: string;

  @ApiProperty({ example: '2026-06-10T12:00:00.000Z' })
  updated_at!: string;

  // ── flow-init extras (only returned on POST initiate) ──────────────────

  @ApiProperty({
    example: 'https://pay.halykbank.kz/checkout/abc123',
    nullable: true,
    description:
      'Provider redirect URL (present on initiation for async providers).',
    required: false,
  })
  redirect_url?: string | null;

  @ApiProperty({
    example: 'kaspi://pay?id=abc123',
    nullable: true,
    description: 'Mobile deeplink (present on initiation for Kaspi Pay).',
    required: false,
  })
  deeplink?: string | null;
}

export class PaymentListResponseDto {
  @ApiProperty({ type: [PaymentResponseDto] })
  items!: PaymentResponseDto[];

  @ApiProperty({ example: null, nullable: true })
  next_cursor!: string | null;
}

// ── prepayment preview ─────────────────────────────────────────────────────

class PrepaymentPreviewDto {
  @ApiProperty({
    example: 360000,
    description: 'Total base amount for the prepayment period in KZT.',
  })
  base_amount!: number;

  @ApiProperty({ example: 10, description: 'Discount percentage applied.' })
  discount_pct!: number;

  @ApiProperty({ example: 324000, description: 'Final amount after discount.' })
  final_amount!: number;

  @ApiProperty({
    example: { from: '2026-06-01', to: '2026-08-31' },
    description: 'ISO date range covered by this prepayment.',
  })
  covers_period!: { from: string; to: string };
}

export class InitiatePrepaymentResponseDto {
  @ApiProperty({ example: 'i1a2b3c4-0005-0005-0005-000000000005' })
  invoice_id!: string;

  @ApiProperty({ example: 'pa1b2c3d-0007-0007-0007-000000000007' })
  payment_id!: string;

  @ApiProperty({
    example: 'https://pay.halykbank.kz/checkout/abc123',
    nullable: true,
  })
  redirect_url!: string | null;

  @ApiProperty({
    example: 'kaspi://pay?...',
    nullable: true,
    required: false,
    description:
      'Provider deeplink (Kaspi). The only way the parent pays a Kaspi prepayment.',
  })
  deeplink?: string | null;

  @ApiProperty({ type: PrepaymentPreviewDto })
  preview!: PrepaymentPreviewDto;
}

// ── manual mark paid response ──────────────────────────────────────────────

export class ManualMarkPaidResponseDto {
  @ApiProperty({ example: 'i1a2b3c4-0005-0005-0005-000000000005' })
  invoice_id!: string;

  @ApiProperty({ example: 'pa1b2c3d-0007-0007-0007-000000000007' })
  payment_id!: string;

  @ApiProperty({ example: 'paid', enum: ['pending', 'partial', 'paid'] })
  new_status!: string;
}

export class CancelInvoiceResponseDto {
  @ApiProperty({ example: 'i1a2b3c4-0005-0005-0005-000000000005' })
  id!: string;

  @ApiProperty({ example: 'cancelled' })
  status!: 'cancelled';
}

// ── initiate payment response (simple, without full PaymentResponseDto) ────

export class InitiatePaymentResponseDto {
  @ApiProperty({ example: 'pa1b2c3d-0007-0007-0007-000000000007' })
  payment_id!: string;

  @ApiProperty({
    example: 'https://pay.halykbank.kz/checkout/abc123',
    nullable: true,
    description: 'Provider redirect URL. Null for mock/cash.',
  })
  redirect_url!: string | null;

  @ApiProperty({
    example: null,
    nullable: true,
    description: 'Mobile deeplink. Null for non-mobile providers.',
  })
  deeplink!: string | null;
}
