import { ApiProperty } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import {
  IsIn,
  IsISO8601,
  IsObject,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  ValidateIf,
} from 'class-validator';
import { normalizeLegacyKzLocale } from '../../../../shared-kernel/utils/i18n-locale-normalizer';

export class CreateContentDto {
  @ApiProperty({
    example: 'news',
    description:
      'Content type. `birthday` is normally auto-generated by cron; admin may create manually.',
    enum: ['news', 'menu', 'schedule_pub', 'qundylyq', 'birthday'],
  })
  @IsIn(['news', 'menu', 'schedule_pub', 'qundylyq', 'birthday'])
  content_type!: string;

  @ApiProperty({
    example: 'all',
    description:
      'Targeting mode. `all` broadcasts to everyone; `group` or `child` narrows.',
    enum: ['all', 'group', 'child'],
  })
  @IsIn(['all', 'group', 'child'])
  target_type!: string;

  @ApiProperty({
    example: '550e8400-e29b-41d4-a716-446655440000',
    description: 'Required when target_type=group.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @ValidateIf((o: CreateContentDto) => o.target_type === 'group')
  @IsUUID()
  target_group_id?: string | null;

  @ApiProperty({
    example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    description: 'Required when target_type=child.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @ValidateIf((o: CreateContentDto) => o.target_type === 'child')
  @IsUUID()
  target_child_id?: string | null;

  @ApiProperty({
    example: 'Важное объявление',
    description: 'Legacy single-locale title (pre-i18n fallback).',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsString()
  @MaxLength(500)
  title?: string | null;

  @ApiProperty({
    example: 'Просим всех родителей ознакомиться с новыми правилами.',
    description: 'Legacy single-locale body.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsString()
  body?: string | null;

  @ApiProperty({
    example: { ru: 'Важное объявление', kk: 'Маңызды хабарландыру' },
    description: 'Localised title map, e.g. { ru, kk }.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @Transform(({ value }) => normalizeLegacyKzLocale(value))
  @IsObject()
  title_i18n?: Record<string, string> | null;

  @ApiProperty({
    example: {
      ru: 'Просим всех родителей ознакомиться с новыми правилами.',
      kk: 'Барлық ата-аналарды жаңа ережелермен таныса беруін сұраймыз.',
    },
    description: 'Localised body map.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @Transform(({ value }) => normalizeLegacyKzLocale(value))
  @IsObject()
  body_i18n?: Record<string, string> | null;

  @ApiProperty({
    example: { month: '2026-05', theme: 'Kindness' },
    description:
      'Arbitrary metadata JSONB. For qundylyq: { month, theme }. For birthday: auto-populated by service.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsObject()
  metadata?: Record<string, unknown> | null;

  @ApiProperty({
    example: '2026-05-10T07:00:00.000Z',
    description:
      'If provided, post is created in scheduled status (must be in the future).',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsISO8601()
  scheduled_for?: string | null;

  @ApiProperty({
    example: '2026-05-17T23:59:59.000Z',
    description: 'Post expiry. Null means no expiry.',
    required: false,
    nullable: true,
  })
  @IsOptional()
  @IsISO8601()
  expires_at?: string | null;
}
