import { ActivityEvent } from '../../domain/entities/activity-event.entity';
import { ActivityEventStatusValue } from '../../domain/value-objects/activity-event-status.vo';

export interface ListActivityEventsFilter {
  groupId?: string;
  /** Inclusive lower bound on `starts_at` (UTC). */
  from?: Date;
  /** Exclusive upper bound on `starts_at` (UTC). */
  to?: Date;
  status?: ActivityEventStatusValue;
}

/**
 * Port over `activity_events`. Status transitions are persisted by reading
 * the aggregate, mutating it, then calling `update`. No partial-update
 * primitives — keeps the contract narrow.
 */
export abstract class ActivityEventRepository {
  abstract create(
    kindergartenId: string,
    event: ActivityEvent,
  ): Promise<ActivityEvent>;

  abstract findById(
    kindergartenId: string,
    eventId: string,
  ): Promise<ActivityEvent | null>;

  abstract update(
    kindergartenId: string,
    event: ActivityEvent,
  ): Promise<ActivityEvent>;

  /**
   * Conditional UPDATE that guards the `status` column against concurrent
   * transitions. Persists the same fields as `update`, but only when the row's
   * current `status` still equals `expectedOldStatus`. Returns `true` when
   * exactly 1 row was affected (the caller won the race) and `false` when 0
   * rows were affected (a concurrent transition already moved the row to a
   * different status — the caller lost the race and the service layer should
   * surface a 409 conflict).
   *
   * Used by `startEvent` / `completeEvent` / `cancelEvent` to close the
   * read-validate-update lost-update race that simple `update` exposes
   * (two concurrent admin clicks can both pass domain validation against the
   * same source status, then both blindly UPDATE — last writer wins).
   */
  abstract updateWithExpectedStatus(
    kindergartenId: string,
    event: ActivityEvent,
    expectedOldStatus: ActivityEventStatusValue,
  ): Promise<boolean>;

  abstract list(
    kindergartenId: string,
    filter: ListActivityEventsFilter,
  ): Promise<ActivityEvent[]>;

  abstract delete(kindergartenId: string, eventId: string): Promise<void>;

  /**
   * Bulk-insert events generated by `copyWeekToNext`. Implementations may
   * use a single `INSERT … VALUES (…) RETURNING *` for performance.
   */
  abstract createMany(
    kindergartenId: string,
    events: ActivityEvent[],
  ): Promise<ActivityEvent[]>;
}
