import { ActivityEvent } from '../../domain/entities/activity-event.entity';
import { ActivityEventStatusValue } from '../../domain/value-objects/activity-event-status.vo';

export interface ListActivityEventsFilter {
  groupId?: string;
  /** Inclusive lower bound on `starts_at` (UTC). */
  from?: Date;
  /** Exclusive upper bound on `starts_at` (UTC). */
  to?: Date;
  status?: ActivityEventStatusValue;
}

/**
 * Port over `activity_events`. Status transitions are persisted by reading
 * the aggregate, mutating it, then calling `update`. No partial-update
 * primitives — keeps the contract narrow.
 */
export abstract class ActivityEventRepository {
  abstract create(
    kindergartenId: string,
    event: ActivityEvent,
  ): Promise<ActivityEvent>;

  abstract findById(
    kindergartenId: string,
    eventId: string,
  ): Promise<ActivityEvent | null>;

  abstract update(
    kindergartenId: string,
    event: ActivityEvent,
  ): Promise<ActivityEvent>;

  /**
   * Conditional UPDATE that guards the `status` column against concurrent
   * transitions. Persists the same fields as `update`, but only when the row's
   * current `status` still equals `expectedOldStatus`. Returns `true` when
   * exactly 1 row was affected (the caller won the race) and `false` when 0
   * rows were affected (a concurrent transition already moved the row to a
   * different status — the caller lost the race and the service layer should
   * surface a 409 conflict).
   *
   * Used by `startEvent` / `completeEvent` / `cancelEvent` to close the
   * read-validate-update lost-update race that simple `update` exposes
   * (two concurrent admin clicks can both pass domain validation against the
   * same source status, then both blindly UPDATE — last writer wins).
   */
  abstract updateWithExpectedStatus(
    kindergartenId: string,
    event: ActivityEvent,
    expectedOldStatus: ActivityEventStatusValue,
  ): Promise<boolean>;

  abstract list(
    kindergartenId: string,
    filter: ListActivityEventsFilter,
  ): Promise<ActivityEvent[]>;

  abstract delete(kindergartenId: string, eventId: string): Promise<void>;

  /**
   * Bulk-insert events generated by `copyWeekToNext`. Implementations may
   * use a single `INSERT … VALUES (…) RETURNING *` for performance.
   */
  abstract createMany(
    kindergartenId: string,
    events: ActivityEvent[],
  ): Promise<ActivityEvent[]>;

  /**
   * Bulk-delete the template-projected, still-scheduled, still-future events of
   * one group inside one week. The sweep half of
   * `ScheduleService.rematerializeFutureWeeks`.
   *
   * Deletes exactly the rows matching ALL of:
   *   - `kindergarten_id = kindergartenId` AND `group_id = groupId`
   *   - `origin = 'template'` — ad-hoc events are never touched. Note this
   *     matches template ORPHANS too (`template_slot_id IS NULL` after a slot
   *     delete NULLed the FK); `origin` is write-once, so it is the only thing
   *     that still identifies them. Sweeping them is the point.
   *   - `status = 'scheduled'` — anything started/completed/cancelled is history.
   *   - `starts_at >= from` AND `starts_at < to` — the target week, half-open.
   *   - `starts_at > after` — preserves events that already began, so the current
   *     week can be rebuilt from `now` forward without rewriting its past.
   *
   * Returns the number of rows deleted. Implementations MUST issue a single
   * DELETE rather than read-then-delete.
   */
  abstract deleteTemplateScheduledInRange(
    kindergartenId: string,
    groupId: string,
    from: Date,
    to: Date,
    after: Date,
  ): Promise<number>;
}
