import { ActivityEvent } from '../../domain/entities/activity-event.entity';
import { ActivityEventStatusValue } from '../../domain/value-objects/activity-event-status.vo';

export interface ListActivityEventsFilter {
  groupId?: string;
  /** Inclusive lower bound on `starts_at` (UTC). */
  from?: Date;
  /** Exclusive upper bound on `starts_at` (UTC). */
  to?: Date;
  status?: ActivityEventStatusValue;
}

/**
 * Port over `activity_events`. Status transitions are persisted by reading
 * the aggregate, mutating it, then calling `update`. No partial-update
 * primitives — keeps the contract narrow.
 */
export abstract class ActivityEventRepository {
  abstract create(
    kindergartenId: string,
    event: ActivityEvent,
  ): Promise<ActivityEvent>;

  abstract findById(
    kindergartenId: string,
    eventId: string,
  ): Promise<ActivityEvent | null>;

  abstract update(
    kindergartenId: string,
    event: ActivityEvent,
  ): Promise<ActivityEvent>;

  abstract list(
    kindergartenId: string,
    filter: ListActivityEventsFilter,
  ): Promise<ActivityEvent[]>;

  abstract delete(kindergartenId: string, eventId: string): Promise<void>;

  /**
   * Bulk-insert events generated by `copyWeekToNext`. Implementations may
   * use a single `INSERT … VALUES (…) RETURNING *` for performance.
   */
  abstract createMany(
    kindergartenId: string,
    events: ActivityEvent[],
  ): Promise<ActivityEvent[]>;
}
