import * as crypto from 'crypto';
import {
  QRPAY_XSH,
  buildXSignInput,
  computeTokenSnMac,
  computeXSU,
  deriveEcdhSecret,
  ecSign,
  generateEcdhKeyPair,
} from './kaspi-crypto';

/**
 * Golden vectors captured from the REVERSE-ENGINEERED reference algorithm
 * (`kaspi_pay_test/src/crypto.js` + `helpers.js`), generated by a throwaway node
 * script running the reference logic verbatim with the fixed inputs below. These
 * frozen constants prove the TypeScript port reproduces the reference
 * byte-for-byte. Do NOT regenerate or "fix" these — a mismatch means the port
 * diverged from live Kaspi semantics.
 *
 * Fixed inputs:
 *   tokenSN = 'TESTTOKEN12345678'
 *   secret  = 00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff (32B)
 *   nowMs   = 1717500000000
 *   url     = 'https://qrpay.kaspi.kz/qrpay/v02/remote/details?operationId=12345'
 */

const FIXED = {
  tokenSN: 'TESTTOKEN12345678',
  secretHex: '00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff',
  nowMs: 1717500000000,
  url: 'https://qrpay.kaspi.kz/qrpay/v02/remote/details?operationId=12345',
};

const GOLDEN = {
  MAC: '763293',
  MAC_NULL: '000000',
  ECDH_SECRET_HEX:
    '2fdabd84747dbf08141d33bb8cdcc1e7380ab2b0e6383835f9849b292f959a65',
  XSU_MD5: '319925652bcb191db5291a28c27dd36f',
  XSIGN_INPUT:
    '/qrpay/v02/remote/details?operationId=12345AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEEDEVICE-AAAA-BBBB-CCCC18.510762026-06-04T19:00:00.123+05:00TESTTOKEN123456784.110.1763293notConnected987INSTALL-1111-2222-3333iOSru-RU2',
};

// Frozen device ECDSA P-256 keypair (PKCS8 / SPKI DER, base64).
const DEVICE_PRIV_B64 =
  'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgwyS1jLl2F+E9yucJNsj4L+ATzbg8t/hQbDzeV8ohcxqhRANCAARv9kFObcHxHydp75nvAJ0+E4/Nyn+ILtpIdFwYXxaQ1hI+wpWyV/IoPb67qVawpz+4uFpnVV9AfuB3G47qsnqy';
const DEVICE_PUB_B64 =
  'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEb/ZBTm3B8R8nae+Z7wCdPhOPzcp/iC7aSHRcGF8WkNYSPsKVslfyKD2+u6lWsKc/uLhaZ1VfQH7gdxuO6rJ6sg==';

// Frozen ECDH pair (client PKCS8 DER priv b64, server SPKI DER pub b64).
const CLIENT_PRIV_B64 =
  'MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgXo28RjflQZ7fDf4G0fou8anmGCDFZPHTxYtHBU99mp2hRANCAAQAaswJoGj2bZsOqfNZi2hNvC158P3UNwCYg9u8aIvqXTwiwi7p9FJxOComYURasYNWkfEwAESlkDjhWFQ3fNZU';
const SERVER_PUB_B64 =
  'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAETiNvJykf+8+61mhIMons0sgbvCGSpj56HEE0GZncniPxS6Eg0OCM2R1Z7DhYf7NlOJ560eH0EsErtxt1C3V4eQ==';

// Header fixture used for the X-Sign signing-input test (pinned field values).
const HEADERS_FIXTURE: Record<string, string> = {
  'X-Kb-TokenSn': 'TESTTOKEN12345678',
  'X-Kb-TokenSnMac': '763293',
  'X-PI': '987',
  'X-Install-ID': 'INSTALL-1111-2222-3333',
  'X-Device-ID': 'DEVICE-AAAA-BBBB-CCCC',
  'X-App-Ver': '4.110.1',
  'X-App-Bld': '1076',
  'X-Platform-Type': 'iOS',
  'X-Platform-Ver': '18.5',
  'X-Locale': 'ru-RU',
  'X-Time': '2026-06-04T19:00:00.123+05:00',
  'X-Request-ID': 'AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE',
  'X-Call': 'notConnected',
  'X-SV': '2',
  'X-SH': QRPAY_XSH,
};

describe('kaspi-crypto', () => {
  describe('computeTokenSnMac', () => {
    it('reproduces the reference OCRA/TOTP MAC for a pinned tokenSN + secret + time', () => {
      const secret = Buffer.from(FIXED.secretHex, 'hex');
      expect(computeTokenSnMac(FIXED.tokenSN, secret, FIXED.nowMs)).toBe(
        GOLDEN.MAC,
      );
    });

    it('returns 000000 when the secret is null', () => {
      expect(computeTokenSnMac(FIXED.tokenSN, null, FIXED.nowMs)).toBe(
        GOLDEN.MAC_NULL,
      );
    });
  });

  describe('deriveEcdhSecret', () => {
    it('reproduces the reference ECDH shared secret for a pinned keypair', () => {
      const secret = deriveEcdhSecret(CLIENT_PRIV_B64, SERVER_PUB_B64);
      expect(secret.toString('hex')).toBe(GOLDEN.ECDH_SECRET_HEX);
    });
  });

  describe('generateEcdhKeyPair', () => {
    it('returns fresh P-256 material whose derived secret matches the saved-key path', () => {
      const a = generateEcdhKeyPair();
      const b = generateEcdhKeyPair();
      expect(a.publicSpkiB64).toBe(a.publicKeyDerB64);
      // Two independently-derived secrets (A.priv×B.pub and B.priv×A.pub) agree —
      // confirms the SPKI/PKCS8 DER encodings round-trip through deriveEcdhSecret.
      const s1 = deriveEcdhSecret(a.privateKeyDerB64, b.publicKeyDerB64);
      const s2 = deriveEcdhSecret(b.privateKeyDerB64, a.publicKeyDerB64);
      expect(s1.toString('hex')).toBe(s2.toString('hex'));
    });
  });

  describe('computeXSU', () => {
    it('reproduces the reference computeXSU md5 for a pinned url', () => {
      expect(computeXSU(FIXED.url)).toBe(GOLDEN.XSU_MD5);
    });
  });

  describe('buildXSignInput', () => {
    it('builds the exact X-Sign signing input string in X-SH order', () => {
      expect(buildXSignInput(FIXED.url, HEADERS_FIXTURE, QRPAY_XSH)).toBe(
        GOLDEN.XSIGN_INPUT,
      );
    });
  });

  describe('ecSign', () => {
    it('produces an X-Sign signature that verifies against the device public key', () => {
      const privateKey = crypto.createPrivateKey({
        key: Buffer.from(DEVICE_PRIV_B64, 'base64'),
        format: 'der',
        type: 'pkcs8',
      });
      const publicKey = crypto.createPublicKey({
        key: Buffer.from(DEVICE_PUB_B64, 'base64'),
        format: 'der',
        type: 'spki',
      });
      const input = buildXSignInput(FIXED.url, HEADERS_FIXTURE, QRPAY_XSH);
      const sig = ecSign(input, privateKey);
      const ok = crypto.verify(
        'SHA256',
        Buffer.from(input),
        publicKey,
        Buffer.from(sig, 'base64'),
      );
      expect(ok).toBe(true);
    });
  });
});
