import { Column, Entity, PrimaryColumn } from 'typeorm';
import {
  ContentStatus,
  ContentTargetType,
  ContentType,
  LocalisedText,
} from '../../../../domain/entities/content-post.entity';

/**
 * TypeORM entity for `content_posts` (B17 §9). Mirrors the migration
 * `1777890002000-B17ContentAndStories.ts` exactly.
 *
 * Notes:
 *   - `id` is generated by PG (`gen_random_uuid()` default) but inserts go
 *     through the domain layer which already produces a UUID; we use
 *     `@PrimaryColumn` for explicit-id INSERTs and rely on the DB default
 *     for direct SQL paths.
 *   - JSONB columns are typed as `LocalisedText | null` /
 *     `Record<string, unknown> | null` — domain mapper hydrates them
 *     verbatim.
 *   - `media_urls` is a Postgres `text[]` — exposed as `string[] | null`.
 */
@Entity({ name: 'content_posts' })
export class ContentPostRelationalEntity {
  @PrimaryColumn('uuid')
  id!: string;

  @Column({ name: 'kindergarten_id', type: 'uuid' })
  kindergarten_id!: string;

  @Column({
    name: 'content_type',
    type: 'enum',
    enum: ['news', 'menu', 'schedule_pub', 'qundylyq', 'birthday'],
    enumName: 'content_type',
  })
  content_type!: ContentType;

  @Column({
    name: 'target_type',
    type: 'enum',
    enum: ['all', 'group', 'child'],
    enumName: 'content_target_type',
    default: 'all',
  })
  target_type!: ContentTargetType;

  @Column({ name: 'target_group_id', type: 'uuid', nullable: true })
  target_group_id!: string | null;

  @Column({ name: 'target_child_id', type: 'uuid', nullable: true })
  target_child_id!: string | null;

  @Column({ name: 'title', type: 'varchar', length: 500, nullable: true })
  title!: string | null;

  @Column({ name: 'body', type: 'text', nullable: true })
  body!: string | null;

  @Column({ name: 'title_i18n', type: 'jsonb', nullable: true })
  title_i18n!: LocalisedText | null;

  @Column({ name: 'body_i18n', type: 'jsonb', nullable: true })
  body_i18n!: LocalisedText | null;

  @Column({ name: 'media_urls', type: 'text', array: true, nullable: true })
  media_urls!: string[] | null;

  @Column({ name: 'metadata', type: 'jsonb', nullable: true })
  metadata!: Record<string, unknown> | null;

  @Column({ name: 'scheduled_for', type: 'timestamptz', nullable: true })
  scheduled_for!: Date | null;

  @Column({ name: 'published_at', type: 'timestamptz', nullable: true })
  published_at!: Date | null;

  @Column({ name: 'expires_at', type: 'timestamptz', nullable: true })
  expires_at!: Date | null;

  @Column({
    name: 'status',
    type: 'enum',
    enum: ['draft', 'scheduled', 'published'],
    enumName: 'content_status',
    default: 'draft',
  })
  status!: ContentStatus;

  @Column({ name: 'created_by', type: 'uuid', nullable: true })
  created_by!: string | null;

  @Column({ name: 'created_at', type: 'timestamptz' })
  created_at!: Date;

  @Column({ name: 'updated_at', type: 'timestamptz' })
  updated_at!: Date;
}
